version: '3'

services:
    nginx:
        restart: always
        image: nginx:1.11.6-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/django
    mysql:
        environment:
          - MYSQL_ROOT_PASSWORD=root
        restart: always
        image: mysql:5.7
        ports:
            - 3306:3306
        network_mode: "host"
        volumes:
          - ./docker/mysql/:/docker-entrypoint-initdb.d
    redis:
        command: redis-server /redis.conf
        image: redis:3.0
        ports:
          - 6379:6379
        restart: always
        network_mode: "host"
        volumes:
          - ./docker/mysql/redis.conf:/redis.conf
    backend:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/django
        entrypoint:
            - /django-entrypoint.sh
        tty: true
        network_mode: "host"
        expose:
            - 8000
    frontend:
        restart: always
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        links:
            - backend
        volumes:
            - .:/django
            - /django/node_modules
        entrypoint:
            - /web-entrypoint.sh
        tty: true

     
    
